config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  post '/colleges/import' => 'colleges#import'

  post '/colleges/:college_id/residence_halls/import' => 'residence_halls#import'

  post '/residents/csv' => 'residents#csv'

  post '/residents/import' => 'residents#import'

  namespace :api do 
    namespace :v1 do 
      resources :colleges do
        resources :residence_halls do
          resources :rooms
        end
      end
      resources :residents
    end
  end


  root 'pages#index'
end

app/models/residence_hall.rb
class ResidenceHall < ApplicationRecord
    require 'csv'
    belongs_to :college
    has_many :rooms, dependent: :destroy

    def self.import(file, college_id)
        CSV.foreach(file.path, headers: true) do |row|
            ResidenceHall.create!(name: row, college_id: college_id)
        end
    end
end

app/controllers/api/v1/residence_halls_controller.rb
class Api::V1::ResidenceHallsController < ApplicationController
    before_action :get_college
    before_action :set_residence_hall, only: [:show, :edit, :update, :destroy]

    # BUG: Missing Template
    def index
        @residence_halls = @college.residence_halls
    end

    # GET /colleges/:college_id/residence_halls/:id
    # GET /colleges/:college_id/residence_halls/:id.json
    def show 
        @rooms = @residence_hall.rooms
        respond_to do |format|
            format.html 
            format.js 
            format.json {
                render :json => @rooms.to_json
            }
        end
    end

    def new
        @residence_hall = @college.residence_halls.build
    end
    
    def edit 
    end

    def create
        @residence_hall = @college.residence_halls.build(residence_hall_params)
        if @residence_hall.save
            redirect_to @college
        end
    end

    def update
        @residence_hall.update!(residence_hall_params)
        redirect_to @college   
    end

    def destroy
        @residence_hall.destroy
        redirect_to @college
    end

    def import
        ResidenceHall.import(params[:file], params[:college_id])
        redirect_to @college
    end
    
    private
    def get_college 
        @college = College.find(params[:college_id])
    end
    def set_residence_hall 
        @residence_hall = @college.residence_halls.find(params[:id])
    end
    def residence_hall_params
        params.require(:residence_hall).permit(:name, :college_id)
    end
end

app/controllers/residence_halls_controller.rb
class ResidenceHallsController < ApplicationController
    before_action :get_college
    before_action :set_residence_hall, only: [:show, :edit, :update, :destroy]

    # BUG: Missing Template
    def index
        @residence_halls = @college.residence_halls
    end

    # GET /colleges/:college_id/residence_halls/:id
    # GET /colleges/:college_id/residence_halls/:id.json
    def show 
        @rooms = @residence_hall.rooms
        respond_to do |format|
            format.html 
            format.js 
            format.json {
                render :json => @rooms.to_json
            }
        end
    end

    def new
        @residence_hall = @college.residence_halls.build
    end
    
    def edit 
    end

    def create
        @residence_hall = @college.residence_halls.build(residence_hall_params)
        if @residence_hall.save
            redirect_to @college
        end
    end

    def update
        @residence_hall.update!(residence_hall_params)
        redirect_to @college   
    end

    def destroy
        @residence_hall.destroy
        redirect_to @college
    end

    def import
        ResidenceHall.import(params[:file], params[:college_id])
        redirect_to @college
    end
    
    private
    def get_college 
        @college = College.find(params[:college_id])
    end
    def set_residence_hall 
        @residence_hall = @college.residence_halls.find(params[:id])
    end
    def residence_hall_params
        params.require(:residence_hall).permit(:name, :college_id)
    end
end

app/helpers/residence_halls_helper.rb
module ResidenceHallsHelper
end

app/views/residence_halls/_form.html.erb
<%= form_with(model: [@college, residence_hall], local: true) do |f| %>
    <div class="field">
        <%= f.label :name %>
        <%= f.text_field :name %>
    </div>
    <div class="actions">
        <%= f.submit %>
    </div>
<% end %>

app/views/residence_halls/edit.html.erb
<div class="heading">
    <h2>Edit Residence Hall</h2>
    <div class="options">
        <%= link_to "Cancel", :back %>
    </div>
</div>
<div class="form">
    <h3><%= @college.name %></h3>
    <%= render 'form', residence_hall: @residence_hall %>
</div>

app/views/residence_halls/new.html.erb
<div class="heading">
    <h2>New Residence Hall</h2>
    <div class="options">
        <%= link_to "Cancel", :back %>
    </div>
</div>
<div class="form">
    <h3><%= @college.name %></h3>
    <%= render 'form', residence_hall: @residence_hall %>
</div>
<hr>
<div class="import">
    <h3>Import</h3>
    <%= form_tag "/colleges/#{@residence_hall.college_id}/residence_halls/import", multipart: true do %>
        <%= file_field_tag :file %>
        <%= submit_tag "Import CSV" %>
    <% end %>
    <h3>Example CSV: </h3>
    <div class="code">
        <p>name<br/>Residence Hall 1<br/>Residence Hall 2<br/>Residence Hall 3</p>
    </div>
</div>

app/views/residence_halls/show.html.erb
<%= link_to college_path(@college) do %>
    <h2><%= @college.name%></h2>
<% end %>
<div class="heading">
    <h2><%= @residence_hall.name%>: Rooms (<%= @rooms.length %>)</h2>
    <div class="options">
        <%= link_to "Edit", edit_college_residence_hall_path(@college, @residence_hall) %>
        <%= link_to "New", new_college_residence_hall_room_path(@college, @residence_hall) %>
    </div>
</div>

<% @rooms.each do |room| %>
    <div class="row">
        <h3><%= room.room_number %></h3>
        <div class="options">
            <%= link_to "View", college_residence_hall_room_path(@college, @residence_hall, room) %>
            <%= link_to "Edit", edit_college_residence_hall_room_path(@college, @residence_hall, room) %>
            <%= link_to "Delete", [@college, @residence_hall, room], method: :delete, data: { confirm: "Are you sure?" }, class: "destructive" %>
        </div>
    </div>
<% end %>

app/views/residence_halls/show.js.erb
$("select#resident_room_id").html("<%= j options_from_collection_for_select(@rooms, :id, :room_number) %>");