config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  post '/colleges/import' => 'colleges#import'

  post '/colleges/:college_id/residence_halls/import' => 'residence_halls#import'

  post '/residents/csv' => 'residents#csv'

  post '/residents/import' => 'residents#import'

  namespace :api do 
    namespace :v1 do 
      resources :colleges do
        resources :residence_halls do
          resources :rooms
        end
      end
      resources :residents
    end
  end


  root 'pages#index'
end

app/models/room.rb
class Room < ApplicationRecord
    belongs_to :residence_hall
    has_many :residents
end

app/controllers/api/v1/rooms_controller.rb
class Api::V1::RoomsController < ApplicationController
    before_action :get_residence_hall
    before_action :get_college
    before_action :set_room, only: [:show, :edit, :update, :destroy]

    def index
        @rooms = @residence_hall.rooms
    end

    def show
        @residents = @room.residents
    end

    def new
        @room = @residence_hall.rooms.build
    end

    def edit
    end

    def create
        @room = @residence_hall.rooms.build(room_params)
        if @room.save
            redirect_to college_residence_hall_path(@college, @residence_hall)
        end
    end

    def update
        @room.update!(room_params)
        redirect_to college_residence_hall_path(@college, @residence_hall)
    end

    def destroy
        @room.destroy
        redirect_to college_residence_hall_path(@college, @residence_hall)
    end

    private
    def get_college 
        @college = College.find(params[:college_id])
    end
    def get_residence_hall
        @residence_hall = ResidenceHall.find(params[:residence_hall_id])
    end
    def set_room
        @room = @residence_hall.rooms.find(params[:id])
    end
    def room_params
        params.require(:room).permit(:room_number, :residence_hall_id)
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
    before_action :get_residence_hall
    before_action :get_college
    before_action :set_room, only: [:show, :edit, :update, :destroy]

    def index
        @rooms = @residence_hall.rooms
    end

    def show
        @residents = @room.residents
    end

    def new
        @room = @residence_hall.rooms.build
    end

    def edit
    end

    def create
        @room = @residence_hall.rooms.build(room_params)
        if @room.save
            redirect_to college_residence_hall_path(@college, @residence_hall)
        end
    end

    def update
        @room.update!(room_params)
        redirect_to college_residence_hall_path(@college, @residence_hall)
    end

    def destroy
        @room.destroy
        redirect_to college_residence_hall_path(@college, @residence_hall)
    end

    private
    def get_college 
        @college = College.find(params[:college_id])
    end
    def get_residence_hall
        @residence_hall = ResidenceHall.find(params[:residence_hall_id])
    end
    def set_room
        @room = @residence_hall.rooms.find(params[:id])
    end
    def room_params
        params.require(:room).permit(:room_number, :residence_hall_id)
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_with(model: [@college, @residence_hall, room], local: true) do |f| %>
    <div class="field">
        <%= f.label :room_number %>
        <%= f.text_field :room_number %>
    </div>
    <div class="actions">
        <%= f.submit %>
    </div>
<% end %>

app/views/rooms/edit.html.erb
<div class="heading">
    <h2>Edit Room</h2>
    <div class="options">
        <%= link_to "Cancel", :back %>
    </div>
</div>
<div class="form">
    <h3><%= @residence_hall.name %></h3>
    <%= render 'form', room: @room %>
</div>

app/views/rooms/new.html.erb
<div class="heading">
    <h2>New Room</h2>
    <div class="options">
        <%= link_to "Cancel", :back %>
    </div>
</div>
<div class="form">
    <h3><%= @residence_hall.name %></h3>
    <%= render 'form', room: @room %>
</div>
<div class="import">
    <h3>Import</h3>
    <%= form_tag "/colleges/#{@residence_hall.college_id}/residence_halls/import", multipart: true do %>
        <%= file_field_tag :file %>
        <%= submit_tag "Import CSV" %>
    <% end %>
    <h3>Example CSV: </h3>
    <div class="code">
        <p>room number<br/>Room 1<br/>Room 2<br/>Room 3</p>
    </div>
</div>

app/views/rooms/show.html.erb
<div class="heading">
    <%= link_to college_residence_hall_path(@college, @residence_hall) do %>
        <h2><%= @residence_hall.name%></h2>
    <% end %>
    <div class="options">
        <div>
            <%= link_to "Edit", edit_college_residence_hall_room_path(@college, @residence_hall, @room) %>
            <%= link_to "Back", :back %>
        </div>
    </div>
</div>
<h3>Room: <%= @room.room_number %></h3>
<% @residents.each do |resident| %>
    <div class="row">
        <h3><%= resident.first_name %> <%= resident.last_name %></h3>
        <p><%= resident.student_id %></p>
        <div class="options">
            <%= link_to "View", resident_path(resident)%>
            <%= link_to "Edit", edit_resident_path(resident)%>
            <%= link_to "Delete", [resident], method: :delete, data: { confirm: "Are you sure?" }, class: "destructive" %>
        </div>
    </div>
<% end %>