config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  post '/colleges/import' => 'colleges#import'

  post '/colleges/:college_id/residence_halls/import' => 'residence_halls#import'

  post '/residents/csv' => 'residents#csv'

  post '/residents/import' => 'residents#import'

  namespace :api do 
    namespace :v1 do 
      resources :colleges do
        resources :residence_halls do
          resources :rooms
        end
      end
      resources :residents
    end
  end


  root 'pages#index'
end

app/models/college.rb
class College < ApplicationRecord
    require 'csv'
    has_many :residence_halls, dependent: :destroy

    def self.import(file)
        CSV.foreach(file.path, headers: true) do |row|
            College.create!(name: row)
        end
    end
end

app/controllers/api/v1/colleges_controller.rb
class Api::V1::CollegesController < ApplicationController
    
    # GET /api/v1/colleges
    def index
        @colleges = College.all.order(name: :asc)
        render json: @colleges
    end

    def new
        @college = College.new
    end

    def create
        @college = College.new(college_params)
        if @college.save 
            redirect_to "/colleges"
        else 
            render '/colleges/new'
        end
    end

    # GET /api/v1/colleges/:id
    def show
        @college = College.find(params[:id])
        @residence_halls = @college.residence_halls
        render json: @residence_halls
    end

    def edit
        @college = College.find(params[:id])
    end

    def update
        @college = College.find(params[:id])
        @college.update!(college_params)
        redirect_to @college        
    end

    def destroy
        @college = College.find(params[:id]).destroy
    end

    def import 
        College.import(params[:file])
        redirect_to root_url
    end

    private
    def college_params
        params.require(:college).permit(:name)
    end
end

app/controllers/colleges_controller.rb
class CollegesController < ApplicationController
    
    # GET /colleges
    # GET /colleges.json
    def index
        @colleges = College.all.order(name: :asc)
        render json: @colleges
    end

    def new
        @college = College.new
    end

    def create
        @college = College.new(college_params)
        if @college.save 
            redirect_to "/colleges"
        else 
            render '/colleges/new'
        end
    end

    # GET /colleges/:id
    # GET /colleges/:id.json
    def show
        @college = College.find(params[:id])
        @residence_halls = @college.residence_halls
        respond_to do |format|
            format.html 
            format.js 
            format.json {
                render :json => @residence_halls.to_json
            }
        end
    end

    def edit
        @college = College.find(params[:id])
    end

    def update
        @college = College.find(params[:id])
        @college.update!(college_params)
        redirect_to @college        
    end

    def destroy
        @college = College.find(params[:id]).destroy
        redirect_to "/colleges"
    end

    def import 
        College.import(params[:file])
        redirect_to root_url
    end

    private
    def college_params
        params.require(:college).permit(:name)
    end
end

app/helpers/colleges_helper.rb
module CollegesHelper
end

app/views/colleges/edit.html.erb
<div class="heading">
    <h2>Edit College</h2>
    <div class="options">
        <%= link_to "Cancel", :back %>
    </div>
</div>
<div class="form">
    <%= form_for(@college) do |f| %>
        <h3>Name</h3>
        <div>
            <%= f.text_field :name %>
            <%= f.submit "Update" %>
        </div>
    <% end %>
</div>

app/views/colleges/import.html.erb
<div class="form">
    <%= form_tag import_users_path, multipart: true do %>
        <div class="field">
            <%= file_field_tag :file %>
        </div>
        <div class="actions">
            <%= submit_tag "Import CSV" %>
        </div>
    <% end %>
    <%= link_to "Cancel", :back %>
</div>

app/views/colleges/index.html.erb
<div class="heading">
    <h2>Colleges (<%= @colleges.length%>)</h2>
    <div class="options">
        <%= link_to "New", "/colleges/new" %>
    </div>
</div>

<% @colleges.each do |college| %>
    <div class="row">
        <h3><%= college.name %></h3>
        <div class="options">
            <%= link_to "View", college_path(college) %>
            <%= link_to "Edit", edit_college_path(college) %>
            <%= link_to "Delete", college, method: :delete, data: { confirm: "Are you sure?" }, class: "destructive" %>
        </div>
    </div>
<% end %>

app/views/colleges/new.html.erb
<div class="heading">
    <h2>New College</h2>
    <div class="options">
        <%= link_to "Cancel", :back %>
    </div>
</div>
<div class="form">
    <%= form_for(@college) do |f| %>
        <div class="field">
            <%= f.label :name %>
            <%= f.text_field :name %>
        </div>
        <div class="actions">
            <%= f.submit "Add" %>
        </div>
    <% end %>
</div>
<hr>
<div class="import">
    <h3>Import</h3>
    <%= form_tag colleges_import_path, multipart: true do %>
        <%= file_field_tag :file %>
        <%= submit_tag "Import CSV" %>
    <% end %>
    <h3>Example CSV: </h3>
    <div class="code">
        <p>name<br/>College 1<br/>College 2<br/>College 3</p>
    </div>
</div>

app/views/colleges/show.html.erb
<div class="heading">
    <h2><%= @college.name%>: Residence Halls (<%= @residence_halls.length%>)</h2>
    <div class="options">
        <%= link_to "Edit", edit_college_path(@college) %>
        <%= link_to "New", new_college_residence_hall_path(@college) %>
    </div>
</div>

<% @residence_halls.each do |residence_hall| %>
    <div class="row">
        <h3><%= residence_hall.name %></h3>
        <div class="options">
            <%= link_to "View", college_residence_hall_path(@college, residence_hall) %>
            <%= link_to "Edit", edit_college_residence_hall_path(@college, residence_hall) %>
            <%= link_to "Delete", [@college, residence_hall], method: :delete, data: { confirm: "Are you sure?" }, class: "destructive" %>
        </div>
    </div>
<% end %>

app/views/colleges/show.js.erb
$("select#resident_residence_hall_id").html("<%= j options_from_collection_for_select(@residence_halls, :id, :name) %>");